name: ci-pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD
    container:
      image: ${{ vars.docker_hub_private_repo }}:latest
      credentials:
          username: ${{ secrets.docker_hub_username}}
          password: ${{ secrets.docker_hub_password}}

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Build
        run: cargo build --all-features --tests
      - name: Test
        run: cargo test
      - name: Clippy
        run: cargo clippy -- -D warnings